### ISSUE TITLE
[Client] Welcome page

### ISSUE THREAD

**Issue by VegasDevApps** [R123NLL/site_coupon_springboot#29]
As a user I want to see all available coupons on welcome page.

You can use as example Customer page.

DOD (Definition of done)

- [x] Non logged user can see available coupons
- [x] When non logged user click on button "Get", user will redirected to login page.
- [x] When logged user clicks on button "Get", coupon should be purchased.
- [x] When coupon is purchased, list of available coupons should be fetched from the server again.

**Comment by R123NLL** [comment]
I did the Welcome page but we have to address the situation of reducing the amount each time
